---
- name: Configure Cisco Routers
  gather_facts: True
  hosts: routers
  connection: network_cli
  #####################################################################################
  ###### Behavioral Inventory Parameters are stored at "group_vars\routers.yml" #######
  #####################################################################################

  vars_prompt:
    - name: uname
      prompt: "Enter Your Username" # Promp the message while asking for user's input
      private: no # Make the text visible to users
    - name: passwd
      prompt: "Enter Your Password"
      private: yes # Make the text invisible to users
      unsafe: yes # Allows special characters input by user. Its required especially in passwords.
    - name: enable_pass
      prompt: "Enter 'enable' Password"
      private: yes
      unsafe: yes
    - name: quest
      prompt: "Do you want to change the password? (type YES or NO in lower cases)"
      private: no
    - name: user
      prompt: "Which user you want to change password for? (type the username in lower cases)"
      private: no
    - name: new_pass
      prompt: "Enter new password for the username {{target_user}}"
      private: yes
      unsafe: yes

  tasks:
    - name: Register the username
      debug: vars="{{user}}"
      register: target_user
    - name: Register the new password
      debug: vars="{{new_pass}}"
      register: target_new_pass
    - name: Changing password of username "{{target_user}}"
      ios_user:
        name: "{{target_user}}"
        privilege: 15
        password_type: secret
        configured_password: "{{target_new_pass}}"
        update_password: always
        state: present
      when: quest == "yes"

    - name: Print the output
      debug: msg="No user account has been modified! Have a great day!"
      when: quest == no
