---
- name: Configure Cisco Routers
  gather_facts: True
  hosts: routers
  connection: network_cli
  #####################################################################################
  ###### Behavioral Inventory Parameters are stored at "group_vars\routers.yml" #######
  #####################################################################################

  vars_prompt:
    - name: uname
      prompt: "Enter Your Username" # Promp the message while asking for user's input
      private: no # Make the text visible to users
    - name: passwd
      prompt: "Enter Your Password"
      private: yes # Make the text invisible to users
      unsafe: yes # Allows special characters input by user. Its required especially in passwords.
    - name: enable_pass
      prompt: "Enter 'enable' Password"
      private: yes
      unsafe: yes
    - name: new_pass
      prompt: "Enter new password for the device"
      private: yes
      unsafe: yes
  tasks:
    - name: Changing password of username {{uname}}
      ios_config:
        save_when: modified
        lines:
          - username avinash privi 15 secret {{new_pass}}
      no_log: true # Will censor the output on the screen and will not document the logs

    - name: Print the output
      debug: msg="Password for Username {{uname}} on all requested devices has been changed!"
