---
- name: Initiating Site Deployment
  gather_facts: no
  hosts: routers
  connection: network_cli
  #####################################################################################
  ###### Behavioral Inventory Parameters are stored at "group_vars\routers.yml" #######
  #####################################################################################

  vars_prompt:
    #####################################################################################
    #####################################################################################
    - name: uname
      prompt: "Enter Your Username" # Promp the message while asking for user's input
      private: no # Make the text visible to users
    - name: passwd
      prompt: "Enter Your Password"
      private: yes # Make the text invisible to users
      unsafe: yes # Allows special characters input by user. Its required especially in passwords.
    - name: enable_pass
      prompt: "Enter 'enable' Password"
      private: yes
      unsafe: yes
    - name: cred_pass
      prompt: "Enter the Password for local credentials"
      private: yes
      unsafe: yes
      encrypt: sha512_crypt
      salt_size: 7
    # #####################################################################################
    # #####################################################################################
    - name: sitecode
      prompt: "Enter the Location's City Code (e.g. rdutr or rduff)" # Promp the message while asking for user's input
      private: no # Make the text visible to users
    # - name: snmplocation
    #   prompt: "Enter the Location's City Name (e.g. Raleigh-Durham (RDU) Intl Airport)" # Promp the message while asking for user's input
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: station_net_24_prefix_1
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.136)"
    #   private: no # Make the text visible to users
    # - name: station_net_24_prefix_2
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.137)"
    #   private: no # Make the text visible to users
    # - name: station_net_24_prefix_3
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.138)"
    #   private: no # Make the text visible to users
    # - name: station_net_24_prefix_4
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.139)"
    #   private: no # Make the text visible to users
    # - name: station_net_24_prefix_5
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.140)"
    #   private: no # Make the text visible to users
    # - name: station_net_24_prefix_6
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.141)"
    #   private: no # Make the text visible to users
    # - name: station_net_24_prefix_7
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.142)"
    #   private: no # Make the text visible to users
    # - name: station_net_24_prefix_8
    #   prompt: "Enter the The first three octets of the first (lowest) /24 of the station's /21 supernet (e.g. 10.43.143)"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    - name: mdf_subloc
      prompt: "Sublocation name for the MDF (core switch stack, wan routers, firewalls, obm). This should be a 'tb' number. Most often this is 'tb1'"
      private: no # Make the text visible to users
    # - name: as1_subloc
    #   prompt: "Sublocation name for access switch stack number 1. This is the first remote closet. If no remote closet, use 'tb2'"
    #   private: no # Make the text visible to users
    # - name: as2_subloc
    #   prompt: "Sublocation name for access switch stack number 2. This is the first remote closet. If no remote closet, use 'tb3'"
    #   private: no # Make the text visible to users
    # - name: as3_subloc
    #   prompt: Sublocation name for access switch stack number 3. This is the first remote closet. If no remote closet, use 'tb4'"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: legacy_subnet_addr_1
    #   prompt: "Legacy subnet #1 addr. Example: '10.42.102.0'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN10 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_subnet_prefixlen_1
    #   prompt: "Legacy subnet #1 prefix length in bits, Example: '24'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN10 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_subnet_netmask_1
    #   prompt: "Legacy subnet #1 network mask, Example: '255.255.255.0'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN10 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_gateway_addr_1
    #   prompt: "Legacy gateway #1 address, Example:  '10.42.102.1'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN10 subnet"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: legacy_subnet_addr_2
    #   prompt: "Legacy subnet #2 addr. Example: '10.42.102.0'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN40 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_subnet_prefixlen_2
    #   prompt: "Legacy subnet #2 prefix length in bits, Example: '24'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN40 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_subnet_netmask_2
    #   prompt: "Legacy subnet #2 network mask, Example: '255.255.255.0'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN40 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_gateway_addr_2
    #   prompt: "Legacy gateway #2 address, Example:  '10.42.102.1'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN40 subnet"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: legacy_subnet_addr_3
    #   prompt: "Legacy subnet #3 addr. Example: '10.42.102.0'. Leave unset if no legacy network being retained. Typically this is used for the legacy VLAN15 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_subnet_prefixlen_3
    #   prompt: "Legacy subnet #3 prefix length in bits, Example: '24'. Leave unset if no legacy network being retained.  Typically this is used for the legacy VLAN15 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_subnet_netmask_3
    #   prompt: "Legacy subnet #3 network mask, Example: '255.255.255.0'. Leave unset if no legacy network being retained.  Typically this is used for the legacy VLAN15 subnet"
    #   private: no # Make the text visible to users
    # - name: legacy_gateway_addr_3
    #   prompt: "Legacy gateway #3 address, Example:  '10.42.102.1'. Leave unset if no legacy network being retained.  Typically this is used for the legacy VLAN15 subnet"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: broadband_subnet_id
    #   prompt: "The subnet ID (e.g. '188.144.96.0') for the station's publicly-addressed broadband assignment. The IPSEC tunnel traffic from the station must originate from this subnet"
    #   private: no # Make the text visible to users
    # - name: broadband_netmask
    #   prompt: "The netmask (e.g. '255.255.255.248') for the station's publicly-addressed broadband assignment. The IPSEC tunnel traffic from the station must originate from this subnet"
    #   private: no # Make the text visible to users
    # - name: broadband_router_a_subif_ip
    #   prompt: "Record this value in the event you statically assign an IP address to your router-a broadband subinterface. Set to 'DHCP' if routers use DHCP to get a broadband address"
    #   private: no # Make the text visible to users
    # - name: broadband_router_b_subif_ip
    #   prompt: "Record this value in the event you statically assign an IP address to your router-b broadband subinterface. Set to 'DHCP' if routers use DHCP to get a broadband address"
    #   private: no # Make the text visible to users
    # - name: broadband_default_gateway
    #   prompt: "Record this value in the event you statically configure a broadband default gateway on your routers. Set to 'DHCP' if routers use DHCP to get a broadband address"
    #   private: no # Make the text visible to users
    # - name: Broadband_bandwidth
    #   prompt: "Enter the Bandwidth of Broadband Connection (e.g. 10 Mpbs)"
    #   private: no # Make the text visible to users
    # - name: Broadband_interrface_des
    #   prompt: "broadband Account and contact Information"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: bgp_as_number
    #   prompt: "Enter the Location's City Code (e.g. rdutr or rduff)" # Promp the message while asking for user's input
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: mpls_a_as_number
    #   prompt: "The remote AS number for the a-side MPLS provider"
    #   private: no # Make the text visible to users
    # - name: mpls_a_bgp_remote_ip
    #   prompt: "The remote address of the a-side MPLS provider PE"
    #   private: no # Make the text visible to users
    # - name: mpls_a_neighbor_desc
    #   prompt: "The description for the a-side MPLS provider"
    #   private: no # Make the text visible to users
    # - name: mpls_a_interface_desc
    #   prompt: "The description for the a-side MPLS interface"
    #   private: no # Make the text visible to users
    # - name: mpls_a_interface_2_desc
    #   prompt: "The description for the a-side MPLS interface #1 (if applicable. typically for second T1 in multilink bundle)"
    #   private: no # Make the text visible to users
    # - name: mpls_a_interface_addr
    #   prompt: "The IP address to use on the a-side MPLS interface"
    #   private: no # Make the text visible to users
    # - name: mpls_a_vlan_tag
    #   prompt: "VLAN ID for the MPLS Broadcast domain (e.g. 10)"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: mpls_b_as_number
    #   prompt: "The remote AS number for the b-side MPLS provider"
    #   private: no # Make the text visible to users
    # - name: mpls_b_bgp_remote_ip
    #   prompt: "The remote address of the b-side MPLS provider PE"
    #   private: no # Make the text visible to users
    # - name: mpls_b_neighbor_desc
    #   prompt: "The description for the b-side MPLS provider"
    #   private: no # Make the text visible to users
    # - name: mpls_b_interface_desc
    #   prompt: "The description for the b-side MPLS interface"
    #   private: no # Make the text visible to users
    # - name: mpls_b_interface_2_desc
    #   prompt: "The description for the b-side MPLS interface #1 (if applicable. typically for second T1 in multilink bundle)"
    #   private: no # Make the text visible to users
    # - name: mpls_b_interface_addr
    #   prompt: "The IP address to use on the b-side MPLS interface"
    #   private: no # Make the text visible to users
    # - name: mpls_b_vlan_tag
    #   prompt: "VLAN ID for the MPLS Broadcast domain (e.g. 10)"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: mpls_a_sprint_mns_ip
    #   prompt: "The Sprint MNS monitoring service IP for wr-1, if applicable (Optional)"
    #   private: no # Make the text visible to users
    # - name: mpls_b_sprint_mns_ip
    #   prompt: "The Sprint MNS monitoring service IP for wr-2, if applicable (Optional)"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: dialin_phone_number
    #   prompt: "The phone number of the POTS line connected to the OpenGear appliance"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: cuse_dmz_subnet
    #   prompt: "The subnet used in the common use DMZ segment. Example: '159.49.14.0'"
    #   private: no # Make the text visible to users
    # - name: cuse_dmz_netmask
    #   prompt: "The netmask used in the common use DMZ segment. Example: '255.255.255.128'"
    #   private: no # Make the text visible to users
    # - name: cuse_dmz_prefixlen
    #   prompt: "The prefix length used in the common use DMZ segment (corresponds to netmask). Example: '25'"
    #   private: no # Make the text visible to users
    # - name: cuse_dmz_fw_addr
    #   prompt: "Our firewall's IP in the common use DMZ. Example: '57.101.23.1'"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: sw1-1_mac_address
    #   prompt: "The MAC address of the first switch in the Agg stack (sw1-1). Find this on the sticker on the back of the switch"
    #   private: no # Make the text visible to users
    # - name: sw1-2_mac_address
    #   prompt: "The MAC address of the second switch in the Agg stack (sw1-2). Find this on the sticker on the back of the switch"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################
    # - name: srt_network_address
    #   prompt: "The network address of the SRT subnet assigned to this station.  Example:  10.47.128.32    All networks should come from 10.47.128.0/21 subnet"
    #   private: no # Make the text visible to users
    # - name: srt_interface_address
    #   prompt: "The SVI interface for the SRT network. (e.g. '10.47.128.33')"
    #   private: no # Make the text visible to users
    # #####################################################################################
    # #####################################################################################

  tasks:
    - import_tasks: 001_router_services.yml
      tags: service_config
    - import_tasks: 002_hostname.yml
      tags: hostname
    - import_tasks: 003_logging.yml
      tags: logging
    - import_tasks: 004_credentials.yml
      tags: credentials
    - import_tasks: 005_system_config.yml
      tags: system_config
